const POSTS_LISTS = [
  {
    id: 1,
    title: "KIARA ARTHA PARK : TEMPAT HEALING MURAH DI BANDUNG",
    url: ".com",
  },
  {
    id: 2,
    title:
      "LAWANGWANGI CREATIVE SPACE : HEALING AESTHETIC DITEMANI KOLEKSI KARYA SENI DAN PEMANDANGAN ASRI KOTA BANDUNG",
    url: ".com",
  },
  {
    id: 3,
    title: "KEINDAHAN MAHAKARYA I NYOMAN NUARTA YANG MEMANJAKAN MATA PARA PENGUNJUNG",
    url: ".com",
  },
  {
    id: 4,
    title:
      "HIDDEN FARM PLANTSHOP CAFE : TEMPAT BERSAHAJA SAMBIL MENIKMATI SEJUKNYA ALAM PERKEBUNAN",
    url: ".com",
  },
  {
    id: 5,
    title: "KINERUKU BANDUNG : SECANGKIR KOPI DAN BUKU UNTUK MENIKMATI SENJA YANG DAMAI",
    url: ".com",
  },
];

export { POSTS_LISTS };
